package supervisor

import (
	"time"

	"Custom-HTS/_legacy/internal/core/pkg/wsrefact_v2/common"
	sess "Custom-HTS/_legacy/internal/core/pkg/wsrefact_v2/session"
)

// Factory is re-exported from the session package for caller convenience:
// supervisor callers configure dial parameters and session runtime
// settings together when constructing a Config.
type Factory = sess.Factory

// WriteRequest is one supervisor-owned websocket write intent.
//
// The caller produces the final payload bytes; supervisor and session
// pass them through unchanged. Freshness-sensitive payloads (nonces,
// timestamps, signatures) must be generated by the caller immediately
// before Enqueue.
type WriteRequest struct {
	// Payload is the raw bytes written to the connection.
	Payload []byte
	// MessageType is the websocket opcode for this request.
	MessageType int
	// WriteTimeout overrides the default websocket write timeout when non-zero.
	WriteTimeout time.Duration
}

// Replayer is the narrow interface exposed to OnReady so the upper layer
// can write replay payloads to a freshly connected session before any
// other goroutine can observe it.
//
// Replayer is valid only for the duration of one OnReady call. Storing
// the reference for use after OnReady returns is undefined: the session
// may be torn down by the supervisor at any time.
type Replayer interface {
	// Send writes one frame to the underlying session synchronously.
	// Same semantics as session.Send: returns nil when the frame has
	// been handed to the OS write buffer; returns ErrNotConnected if
	// the session is shutting down; returns an OperationError on write
	// failure.
	Send(request WriteRequest) error
}

// Hooks delivers lifecycle notifications from the reconnect supervisor.
//
// OnReady and OnEvent have distinct roles by design:
//
//   - OnReady is the side-effect hook for replay and authentication.
//     It runs synchronously after a successful dial, with a Replayer
//     scoped to the new session. The session is NOT yet exposed to
//     external Enqueue callers while OnReady runs: replay frames
//     reach the wire before any external frame can. Returning a
//     non-nil error tells the supervisor that this session is
//     unusable; the supervisor tears it down and proceeds to the
//     next reconnect attempt without ever exposing the session.
//
//   - OnEvent is the observer hook for logging, metrics, and UI. It
//     receives every lifecycle transition. Connected and Reconnected
//     events fire ONLY after OnReady has completed successfully, so
//     observing them means the session is fully ready (replay done,
//     broker state restored).
//
// Replay ordering: because OnReady runs before active is exposed,
// replay frames always reach the wire before any external Enqueue
// frame. Callers do not need to install their own gating; the
// supervisor's lifecycle ordering provides it. Subscribe / send
// requests arriving during the replay window see ErrNotConnected
// from Enqueue, which the caller handles like any other transient
// disconnect (retry, queue, surface to UI).
type Hooks struct {
	// OnReady is invoked after each successful dial, synchronously,
	// with the attempt count (0 for the initial dial, 1+ for reconnects)
	// and a Replayer scoped to the new session.
	//
	// The session is NOT yet exposed via supervisor.active when
	// OnReady runs. Use the supplied Replayer to send frames during
	// this window; supervisor.Enqueue will return ErrNotConnected.
	//
	// Returning a non-nil error aborts session activation: the
	// session is stopped, OnEvent receives a Disconnected event
	// carrying this error, and the supervisor proceeds to the next
	// reconnect attempt. No Connected/Reconnected event fires for
	// this attempt.
	OnReady func(replayer Replayer, attempt int) error
	// OnEvent is invoked for every lifecycle transition.
	OnEvent func(event common.ConnEvent)
}

// Config configures the reconnect supervisor.
type Config struct {
	// Factory builds one configured Session per dial attempt.
	Factory Factory
	// DialTimeout caps a single dial attempt. Zero defaults to 10s.
	// On expiry, the dial is abandoned and the next reconnect attempt
	// proceeds after the backoff interval.
	DialTimeout time.Duration
	// ReconnectMin is the minimum reconnect backoff (defaults to 1s).
	ReconnectMin time.Duration
	// ReconnectMax is the maximum reconnect backoff (defaults to 60s).
	ReconnectMax time.Duration
	// Hooks receives lifecycle notifications.
	Hooks Hooks
}

func (config *Config) applyDefaults() error {
	if config.Factory.URL == "" {
		return common.ErrURLRequired
	}
	if config.DialTimeout <= 0 {
		config.DialTimeout = 10 * time.Second
	}
	if config.ReconnectMin <= 0 {
		config.ReconnectMin = 1 * time.Second
	}
	if config.ReconnectMax <= 0 {
		config.ReconnectMax = 60 * time.Second
	}
	if config.ReconnectMax < config.ReconnectMin {
		config.ReconnectMax = config.ReconnectMin
	}
	config.Hooks = normalizeHooks(config.Hooks)
	return nil
}

func normalizeHooks(hooks Hooks) Hooks {
	if hooks.OnReady == nil {
		hooks.OnReady = func(Replayer, int) error { return nil }
	}
	if hooks.OnEvent == nil {
		hooks.OnEvent = func(common.ConnEvent) {}
	}
	return hooks
}

// sessionReplayer adapts a Session to the Replayer interface, so the
// supervisor can pass the session to OnReady without leaking the full
// session API.
type sessionReplayer struct {
	session *sess.Session
}

func (r sessionReplayer) Send(request WriteRequest) error {
	return r.session.Send(sess.Request{
		Payload:      request.Payload,
		MessageType:  request.MessageType,
		WriteTimeout: request.WriteTimeout,
	})
}
