package supervisor

import (
	"fmt"
	"net/http"
	"time"

	sess "Custom-HTS/internal/core/pkg/wsrefact_v3/session"

	"github.com/gorilla/websocket"
)

// MessageHandler aliases the lower session message callback type for upper callers.
type MessageHandler = sess.MessageHandler

// Handlers aliases the lower session handler set for upper callers.
type Handlers = sess.Handlers

// OperationError aliases the lower session operation error for upper callers.
type OperationError = sess.OperationError

// ConnState represents the connection lifecycle state of the reconnecting transport.
type ConnState int

const (
	// ConnStateStopped reports that the transport is not running.
	ConnStateStopped ConnState = iota
	// ConnStateReconnecting reports that the transport is trying to establish a session.
	ConnStateReconnecting
	// ConnStateConnected reports that the transport currently owns a live session.
	ConnStateConnected
)

// String formats the lifecycle state for debugging and diagnostics.
func (state ConnState) String() string {
	switch state {
	case ConnStateStopped:
		return "Stopped"
	case ConnStateReconnecting:
		return "Reconnecting"
	case ConnStateConnected:
		return "Connected"
	default:
		return fmt.Sprintf("ConnState(%d)", int(state))
	}
}

// ConnEventType identifies one websocket lifecycle event.
type ConnEventType string

const (
	// Connected reports that the first live session became ready.
	Connected ConnEventType = "connected"
	// Reconnected reports that a later live session became ready after a disconnect.
	Reconnected ConnEventType = "reconnected"
	// Disconnected reports that the live session ended.
	Disconnected ConnEventType = "disconnected"
	// Reconnecting reports that the transport is waiting before the next dial attempt.
	Reconnecting ConnEventType = "reconnecting"
)

// ConnEvent reports one websocket lifecycle transition.
type ConnEvent struct {
	// Type identifies the lifecycle transition.
	Type ConnEventType
	// Err carries the lifecycle failure when applicable.
	Err error
	// Attempt stores the reconnect attempt count when applicable.
	Attempt int
	// At is the local time when the event was emitted.
	At time.Time
}

// WriteRequest is one supervisor-owned websocket write intent.
//
// The caller produces the final payload bytes; supervisor and session
// pass them through unchanged. Freshness-sensitive payloads (nonces,
// timestamps, signatures) must be generated by the caller immediately
// before Enqueue.
type WriteRequest struct {
	// Payload is the raw bytes written to the connection.
	Payload []byte
	// MessageType is the websocket opcode for this request.
	MessageType int
	// WriteTimeout overrides the default websocket write timeout when non-zero.
	WriteTimeout time.Duration
}

// Replayer is the narrow interface exposed to OnReady so the upper layer
// can write replay payloads to a freshly connected session before any
// other goroutine can observe it.
//
// Replayer is valid only for the duration of one OnReady call. Storing
// the reference for use after OnReady returns is undefined: the session
// may be torn down by the supervisor at any time.
type Replayer interface {
	// Send writes one frame to the underlying session synchronously.
	// Same semantics as session.Send: returns nil when the frame has
	// been handed to the OS write buffer; returns ErrNotConnected if
	// the session is shutting down; returns an OperationError on write
	// failure.
	Send(request WriteRequest) error
}

// Hooks delivers lifecycle notifications from the reconnect supervisor.
//
// OnReady and OnEvent have distinct roles by design:
//
//   - OnReady is the side-effect hook for replay and authentication.
//     It runs synchronously after a successful dial, with a Replayer
//     scoped to the new session. The session is NOT yet exposed to
//     external Enqueue callers while OnReady runs: replay frames
//     reach the wire before any external frame can. Returning a
//     non-nil error tells the supervisor that this session is
//     unusable; the supervisor tears it down and proceeds to the
//     next reconnect attempt without ever exposing the session.
//
//   - OnEvent is the observer hook for logging, metrics, and UI. It
//     receives every lifecycle transition. Connected and Reconnected
//     events fire ONLY after OnReady has completed successfully, so
//     observing them means the session is fully ready (replay done,
//     broker state restored).
//
// Replay ordering: because OnReady runs before active is exposed,
// replay frames always reach the wire before any external Enqueue
// frame. Callers do not need to install their own gating; the
// supervisor's lifecycle ordering provides it. Subscribe / send
// requests arriving during the replay window see ErrNotConnected
// from Enqueue, which the caller handles like any other transient
// disconnect (retry, queue, surface to UI).
type Hooks struct {
	// OnReady is invoked after each successful dial, synchronously,
	// with the attempt count (0 for the initial dial, 1+ for reconnects)
	// and a Replayer scoped to the new session.
	//
	// The session is NOT yet exposed via supervisor.active when
	// OnReady runs. Use the supplied Replayer to send frames during
	// this window; supervisor.Enqueue will return ErrNotConnected.
	//
	// Returning a non-nil error aborts session activation: the
	// session is stopped, OnEvent receives a Disconnected event
	// carrying this error, and the supervisor proceeds to the next
	// reconnect attempt. No Connected/Reconnected event fires for
	// this attempt.
	OnReady func(replayer Replayer, attempt int) error
	// OnEvent is invoked for every lifecycle transition.
	OnEvent func(event ConnEvent)
}

// Config configures the reconnect supervisor with flattened session-factory settings.
type Config struct {
	// Dialer is the gorilla websocket dialer. Nil falls back to websocket.DefaultDialer.
	Dialer *websocket.Dialer
	// URL is the websocket endpoint URL. Required.
	URL string
	// Header carries optional handshake headers.
	Header http.Header
	// ReadLimit is the maximum inbound frame size in bytes.
	ReadLimit int64
	// PongTimeout is the read deadline extension applied on each pong.
	PongTimeout time.Duration
	// PingInterval controls ping cadence. Zero disables pings.
	PingInterval time.Duration
	// WriteTimeout is the default websocket write timeout.
	WriteTimeout time.Duration
	// Handlers receives synchronous inbound message callbacks.
	Handlers Handlers
	// DialTimeout caps a single dial attempt. Zero defaults to 10s.
	DialTimeout time.Duration
	// ReconnectMin is the minimum reconnect backoff (defaults to 1s).
	ReconnectMin time.Duration
	// ReconnectMax is the maximum reconnect backoff (defaults to 60s).
	ReconnectMax time.Duration
	// Hooks receives lifecycle notifications.
	Hooks Hooks
}

// applyDefaults normalizes reconnect policy and hook defaults.
func (config *Config) applyDefaults() error {
	if config.URL == "" {
		return ErrURLRequired
	}
	if config.DialTimeout <= 0 {
		config.DialTimeout = 10 * time.Second
	}
	if config.ReconnectMin <= 0 {
		config.ReconnectMin = 1 * time.Second
	}
	if config.ReconnectMax <= 0 {
		config.ReconnectMax = 60 * time.Second
	}
	if config.ReconnectMax < config.ReconnectMin {
		config.ReconnectMax = config.ReconnectMin
	}
	config.Hooks = normalizeHooks(config.Hooks)
	return nil
}

// normalizeHooks installs fast no-op callbacks for nil hooks.
func normalizeHooks(hooks Hooks) Hooks {
	if hooks.OnReady == nil {
		hooks.OnReady = func(Replayer, int) error { return nil }
	}
	if hooks.OnEvent == nil {
		hooks.OnEvent = func(ConnEvent) {}
	}
	return hooks
}

// sessionReplayer adapts a Session to the Replayer interface, so the
// supervisor can pass the session to OnReady without leaking the full
// session API.
type sessionReplayer struct {
	// session is the freshly connected live session for one OnReady window.
	session *sess.Session
}

// Send forwards one replay frame to the underlying session.
func (replayer sessionReplayer) Send(request WriteRequest) error {
	return replayer.session.Send(sess.Request{
		Payload:      request.Payload,
		MessageType:  request.MessageType,
		WriteTimeout: request.WriteTimeout,
	})
}
